apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rhtap-415-e2e
spec:
  description: >-
    This is an integration pipeline to deploy Ephemeral cluster
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: 'Test ID corresponding to a defined Konflux integration test'
      name: test-id
      default: ''
    - description: 'Test name corresponding to a defined Konflux integration test'
      name: test-name
      default: ''
    - description: 'Openshift version for epehmeral cluster deployment'
      name: ocp-version
      default: '4.15.9'
      type: string
    - name: test-event-type
      default: 'none'
      description: image tag value will be passed by pipeline from build-image task result
    - name: ocp-login-command
      default: ''
      description: ''
  tasks:
    - name: extract-test-details
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-qe-incubator/konflux-qe-definitions
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test-details-extraction/0.0.1/test-details-extraction.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
    - name: deploy-rosa
      runAfter:
        - "extract-test-details"
      when:
        - input: "$(tasks.extract-test-details.results.test-event-type)"
          operator: in
          values: ["push"]
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-qe-incubator/konflux-qe-definitions
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/deploy-ocp/rosa/0.0.1/rosa-hcp.yaml
      params:
        - name: test-id
          value: $(context.pipelineRun.uid)
        - name: test-name
          value: $(context.pipelineRun.name)
        - name: ocp-version
          value: $(params.ocp-version)
    - name: upload-artifacts
      runAfter:
        - "deploy-rosa"
      when:
        - input: "$(tasks.extract-test-details.results.test-event-type)"
          operator: in
          values: ["push"]
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-qe-incubator/konflux-qe-definitions
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/gather-artifacts/0.0.1/upload-oras.yaml
      params:
        - name: test-id
          value: $(context.pipelineRun.uid)
        - name: test-name
          value: $(context.pipelineRun.name)
        - name: ocp-version
          value: $(params.ocp-version)
        - name: ocp-login-command
          value: $(tasks.deploy-rosa.results.ocp-login-command)
    - name: rhtap-install
      runAfter:
        - "deploy-rosa"
      when:
        - input: "$(tasks.extract-test-details.results.test-event-type)"
          operator: in
          values: ["push"]
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-qe-incubator/konflux-qe-definitions
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/rhtap-installer/rhtap-install.yaml
      params:
        - name: test-id
          value: $(context.pipelineRun.uid)
        - name: test-name
          value: $(context.pipelineRun.name)
        - name: ocp-login-command
          value: $(tasks.deploy-rosa.results.ocp-login-command)