apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  tasks:
    - name: hello-world-task
      taskSpec:
        steps:
          - name: hello-world-step
            image: alpine
            script:
              - echo "Hello, World!"
