apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: test-pipeline
spec:
  description: >-
    This is an integration pipeline example
  params:
    - name: test-task
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/redhat-appstudio/rhtap-e2e
          - name: revision
            value: main
          - name: pathInRepo
            value: integration/task.yaml
